### PR TITLE
Vicerant 

### PR DESCRIPTION
**Pull request by Rockingrajat**

### CODE REVIEW

**Comment by yash-s20** [comment]
Hi. Almost done perfectly. 15 on the main task. However I see a force push on the repository and I don't like it 😅 . Also there seems to be a switch in the order of names happening from commit  ebdcba0 to 19accb5. 3 on the bonus now, 1 more if you give a legitimate reason for the force push.
Total 15 + 3

**Comment by garg-saurav** [comment]
Hi Yash! After doing the main task, we sent you a pull request and started doing the bonus task. But our first commit of bonus task resulted in adding that commit in the previous pull request that we had sent to you. We thought we have to wait for you to merge changes of main task before bonus task and then send the 2nd pull request. So we removed the last commit and force pushed. As you can see there was no error by opening the force push. Later on someone told us that we can add all commits in single pull request. And you do not deduct marks for that. That's why we again completed the bonus task.

**Comment by yash-s20** [comment]
That's fair. 4 bonus. 15 + 4 total

**Comment by Rockingrajat** [comment]
Hi Yash! Actually only the final order was specified in the problem statement for bonus part and so we didn't know that we had to correct the order while resolving conflicts in intermediate steps. Our local content showed up above the new content we'd pulled and we just deleted the extra lines. Kindly have a look at it.

**Pull request merged**
